### PR TITLE
enabling pkgconfig file generation on Windows.

### PR DESCRIPTION
**Pull request by seanyen**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

* Enabling `pkgconfig` file generation for all platforms. (Yup, there is `pkg-config` on Windows too.)

### CODE REVIEW

**Comment by seanyen** [comment]
@conda-forge-admin, please rerender

**Comment by seanyen** [comment]
hmm, conda-build `3.19.2` doesn't detect the prefix in the `.pc` file. Something seems to be broken.

**Comment by seanyen** [comment]
@conda-forge-admin, please rerender

**Comment by seanyen** [comment]
I think there are some issues on the settings between `conda-smithy`, `conda-build` and `miniconda` itself. :/

Here is what happens: `conda-build` uses `rg.exe` to do prefix pattern matching, and [`ripgrep`](https://anaconda.org/conda-forge/ripgrep) is installed along with [`conda-build`](https://github.com/conda-forge/conda-build-feedstock/blob/master/recipe/meta.yaml#L48). `conda-smithy` creates a recipe that installs `conda-build` to the `base` environment. However, `rg.exe` is installed to `C:\Miniconda\bin` but it is not in the `%PATH%` for `base` environment (which is only added for activated, so `conda-build` fails to find `rg.exe` at run-time and fallback to [`regex_files_py`](https://github.com/conda/conda-build/blob/6a986c3efa5ce073696c4982057af4b5e150ee00/conda_build/build.py#L396). But why the `regex_files_py` fails to detect prefix still a mystery for me, but IHMO, the `rg.exe` is preferred to use.

**Comment by seanyen** [comment]
Currently I made a patch to the Azure pipelines YAML to add `C:\Miniconda\bin` to the `%PATH%`, and also amplify the issue here: https://gitter.im/conda-forge/conda-forge.github.io?at=5e883e1a4d7bfa6d3147076e

Hope that will be addressed soon.

**Comment by ryanvolz** [comment]
I commented over at the bug I filled against `conda-build` with a link to this investigative work, but would you say this looks more like a `conda-smithy` bug now?

**Comment by seanyen** [comment]
@ryanvolz I think there are many ways to adddress it. For example, install rg.exe to Library\bin. Or conda-smithy force to create a environment instead of using the base. I am not sure which is the better so I amplified the issue to gitter.

**Comment by seanyen** [comment]
And that’s for sure there are bugs in conda-build too, where the fallback path without rg should also work on Windows.

**Comment by seanyen** [comment]
I will merge this change for a release first.

**Pull request merged**
